import * as THREE from './assets/three.module.js';
const works=[
 {title:'الفتاة ذات القرط اللؤلؤي',artist:'يوهانس فيرمير',period:'العصر الذهبي الهولندي',year:'حوالي 1665',medium:'ألوان زيتية على قماش',location:'ماورتشهاوس، لاهاي',description:'التفاتة عابرة، وضوء يلامس الوجه، ولؤلؤة تختصر المشهد. ليست بورتريه لشخص معروف، بل دراسة لشخصية متخيّلة؛ يترك فيرمير هويتها مفتوحة لتأمّل المشاهد.',src:'pearl.jpg',ratio:.85,url:'https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring/'},
 {title:'ليلة النجوم',artist:'فنسنت فان غوخ',period:'ما بعد الانطباعية',year:'1889',medium:'ألوان زيتية على قماش',location:'متحف الفن الحديث، نيويورك',description:'سماء تتحرّك فوق قرية ساكنة. رسم فان غوخ هذا المشهد في سان ريمي، جامعًا بين المشاهدة والخيال. تتبّع دوامات الأزرق وضوء النجوم، ثم لاحظ شجرة السرو التي تصل الأرض بالسماء.',src:'starry.jpg',ratio:1.263,url:'https://www.moma.org/collection/works/79802'},
 {title:'القُبلة',artist:'غوستاف كليمت',period:'الفن الجديد · المرحلة الذهبية',year:'1907 – 1908',medium:'زيت وورق ذهب على قماش',location:'بلفيدير، فيينا',description:'عناق يحتضنه الذهب. تتداخل الزخارف الهندسية والأشكال الزهرية لتجعل الشخصيتين كأنهما جزء من فسيفساء واحدة. عمل من المرحلة الذهبية لكليمت، يستكشف القرب الإنساني بلغة اللون والزخرفة.',src:'kiss.jpg',ratio:1,url:'https://en.wikipedia.org/wiki/The_Kiss_(Klimt)'}];
const $=s=>document.querySelector(s);let index=0,close=false,renderer,scene,camera,paintingMeshes=[],targetX=0,px=0,py=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
$('.counter span:last-child').textContent=String(works.length).padStart(2,'0');
works.forEach((w,i)=>{const b=document.createElement('button');b.className='thumb';b.setAttribute('aria-label',w.title);b.innerHTML=`<img src="assets/${w.src}" alt="${w.title}">`;b.onclick=()=>select(i);$('.thumbnails').append(b)});
function select(i){index=(i+works.length)%works.length;const w=works[index];for(const key of ['title','artist','period','year','description','medium','location'])$('#'+key).textContent=w[key];$('#source').href=w.url;$('#number').textContent=String(index+1).padStart(2,'0');document.querySelectorAll('.thumb').forEach((b,j)=>{b.classList.toggle('active',index===j);b.setAttribute('aria-current',index===j?'true':'false')});targetX=index*8;if($('.fallback-art')){$('.fallback-art').src='assets/'+w.src;$('.fallback-art').alt=w.title}}
$('#next').onclick=()=>select(index+1);$('#prev').onclick=()=>select(index-1);$('#closer').onclick=()=>{close=!close;document.body.classList.toggle('close-view',close);$('#closer span').textContent=close?'العودة إلى القاعة':'اقترب من اللوحة';$('#closer').setAttribute('aria-pressed',String(close))};
window.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;if(e.key==='ArrowLeft'){e.preventDefault();select(index+1)}if(e.key==='ArrowRight'){e.preventDefault();select(index-1)}if(e.key==='Escape'&&close)$('#closer').click()});
let startX=0,startY=0;$('#scene').addEventListener('pointerdown',e=>{startX=e.clientX;startY=e.clientY});$('#scene').addEventListener('pointerup',e=>{if(Math.abs(e.clientX-startX)>55&&Math.abs(e.clientY-startY)<70)select(index+(e.clientX<startX?1:-1))});window.addEventListener('pointermove',e=>{px=e.clientX/innerWidth-.5;py=e.clientY/innerHeight-.5});
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('#fullscreen').title='ملء الشاشة غير متاح في هذا المتصفح'}};document.addEventListener('fullscreenchange',()=>$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'إنهاء ملء الشاشة':'ملء الشاشة'));
select(0);
try{
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('#scene').append(renderer.domElement);
 scene=new THREE.Scene();scene.background=new THREE.Color('#131c17');scene.fog=new THREE.Fog('#101812',20,55);camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,80);
 const mat=(color,roughness=.8,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const wall=mat('#243a30'),floor=mat('#35372e',.33,.15),gold=mat('#a98648',.28,.72),dark=mat('#141b17');
 function box(x,y,z,w,h,d,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
 box(8,3,-.25,44,6,.4,wall);box(8,-.15,6,44,.3,16,floor);box(8,6,5,44,.15,12,dark);box(8,.13,.04,44,.26,.12,dark);box(8,.28,.06,44,.015,.015,gold);
 for(let x=-14;x<30;x+=4){box(x,3,0,.035,6,.02,mat('#182a21'));box(x,5.65,3,.04,.05,6,dark)}
 // Fine floor joints give the camera movement a clear sense of depth.
 for(let x=-14;x<31;x+=2.4)box(x,.006,6,.008,.008,14,mat('#1e2922'));
 for(let z=1;z<14;z+=2.4)box(8,.009,z,44,.008,.008,mat('#1e2922'));
 scene.add(new THREE.HemisphereLight('#d9e5d9','#242317',1.25));scene.add(new THREE.AmbientLight('#e6c995',.2));
 const loader=new THREE.TextureLoader();let completed=0;
 works.forEach((w,i)=>{const x=i*8,h=2.65,ww=h*w.ratio;box(x,2.9,.1,ww+.28,h+.28,.19,dark);box(x,2.9,.22,ww+.22,h+.22,.16,gold);box(x,2.9,.315,ww+.075,h+.075,.045,mat('#2c2316'));
 const tex=loader.load('assets/'+w.src,()=>{completed++;if(completed===works.length)$('#loading').hidden=true},undefined,()=>{$('#loading').textContent='تعذّر تحميل إحدى الصور';});tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();const art=new THREE.Mesh(new THREE.PlaneGeometry(ww,h),new THREE.MeshBasicMaterial({map:tex}));art.position.set(x,2.9,.344);art.userData.index=i;scene.add(art);paintingMeshes.push(art);
 // Physical frame bevels and a lit museum label.
 box(x-ww/2-.07,2.9,.34,.035,h+.19,.035,gold);box(x+ww/2+.07,2.9,.34,.035,h+.19,.035,gold);box(x,2.9+h/2+.07,.34,ww+.19,.035,.035,gold);box(x,2.9-h/2-.07,.34,ww+.19,.035,.035,gold);
 box(x+ww/2+.38,1.52,.06,.33,.18,.02,mat('#b1b1a0'));
 const light=new THREE.SpotLight('#ffe4b3',65,13,.66,.8,1.4);light.position.set(x,5.5,2);light.target.position.set(x,2.6,0);light.castShadow=true;light.shadow.mapSize.set(1024,1024);scene.add(light,light.target);box(x,5.55,2,.18,.12,.32,dark);
 });
 camera.position.set(.75,3.05,8.3);const look=new THREE.Vector3();let last=performance.now();
 function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.06);last=now;const mobile=innerWidth<=700;const offset=mobile?0:close?0:1.65;const destZ=close?(mobile?6.8:5.6):(mobile?9.8:8.3);const blend=reduced?1:1-Math.exp(-dt*4);camera.position.x+=(targetX+offset-camera.position.x)*blend;camera.position.z+=(destZ-camera.position.z)*blend;camera.position.y=mobile?(close?2.9:1.35):3.05;
 look.set(camera.position.x+(reduced?0:px*.14),mobile?(close?2.9:1.35):2.83+(reduced?0:py*.05),0);camera.lookAt(look);renderer.render(scene,camera)}requestAnimationFrame(animate);
 window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
 const ray=new THREE.Raycaster();renderer.domElement.addEventListener('click',e=>{if(Math.abs(e.clientX-startX)>8)return;const p=new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(p,camera);const hits=ray.intersectObjects(paintingMeshes);if(hits.length){const n=hits[0].object.userData.index;if(index!==n)select(n);else $('#closer').click()}});
}catch(err){console.warn('3D view unavailable',err);$('#loading').hidden=true;const img=document.createElement('img');img.className='fallback-art';img.src='assets/'+works[index].src;img.alt=works[index].title;$('#scene').append(img)}
